from enum import Enum


class ErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    FILE_ERROR = "FILE_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"